<?xml version="1.0" encoding="utf-8"?><Database Name="QLBH_PhanDinhDung" Class="qlbh_dungDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NGOQUANGHOAN;Initial Catalog=QLBH_PhanDinhDung;Integrated Security=True" SettingsObjectName="QLBHTH_PhanDinhDung.Properties.Settings" SettingsPropertyName="QLBH_PhanDinhDungConnectionString4" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CT_Hoadon" Member="CT_Hoadons">
    <Type Name="CT_Hoadon">
      <Column Name="SoHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Mahang" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dongiaban" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Hanghoa_CT_Hoadon" Member="Hanghoa" ThisKey="Mahang" OtherKey="Mahang" Type="Hanghoa" IsForeignKey="true" />
      <Association Name="Hoadon_CT_Hoadon" Member="Hoadon" ThisKey="SoHD" OtherKey="SoHD" Type="Hoadon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Hanghoa" Member="Hanghoas">
    <Type Name="Hanghoa">
      <Column Name="Mahang" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Loaihang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Tenhang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Dongia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Hanghoa_CT_Hoadon" Member="CT_Hoadons" ThisKey="Mahang" OtherKey="Mahang" Type="CT_Hoadon" />
      <Association Name="Loaihang_Hanghoa" Member="Loaihang1" ThisKey="Loaihang" OtherKey="Maloai" Type="Loaihang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Hoadon" Member="Hoadons">
    <Type Name="Hoadon">
      <Column Name="SoHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ngayban" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaKH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Hoadon_CT_Hoadon" Member="CT_Hoadons" ThisKey="SoHD" OtherKey="SoHD" Type="CT_Hoadon" />
      <Association Name="Khachhang_Hoadon" Member="Khachhang" ThisKey="MaKH" OtherKey="MaKH" Type="Khachhang" IsForeignKey="true" />
      <Association Name="Nhanvien_Hoadon" Member="Nhanvien" ThisKey="MaNV" OtherKey="MaNV" Type="Nhanvien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Khachhang" Member="Khachhangs">
    <Type Name="Khachhang">
      <Column Name="MaKH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Quan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ThanhPho" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Khachhang_Hoadon" Member="Hoadons" ThisKey="MaKH" OtherKey="MaKH" Type="Hoadon" />
    </Type>
  </Table>
  <Table Name="dbo.Loaihang" Member="Loaihangs">
    <Type Name="Loaihang">
      <Column Name="Maloai" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tenloai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Loaihang_Hanghoa" Member="Hanghoas" ThisKey="Maloai" OtherKey="Loaihang" Type="Hanghoa" />
    </Type>
  </Table>
  <Table Name="dbo.Nhanvien" Member="Nhanviens">
    <Type Name="Nhanvien">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Matkhau" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Quyen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Nhanvien_Hoadon" Member="Hoadons" ThisKey="MaNV" OtherKey="MaNV" Type="Hoadon" />
    </Type>
  </Table>
</Database>